<!DOCTYPE html>
<html lang="ja-JP">
<head>

<meta name="robots" content="noindex">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="../style.css">
<link rel="stylesheet" href="../syntax-highlight.css">
<link rel="icon" type="image/png" href="../rurema.png">

<title>class Exception (Ruby 3.1.2 リファレンスマニュアル)</title>
<meta name="description" content="全ての例外の祖先のクラスです。">
<script src="../script.js"></script>
</head>
<body>


<header>
  <nav>
    <ol class="inline-breadcrumb-list">
      <li>
        <a href="../doc/index.html">Ruby 3.1.2 リファレンスマニュアル</a>
      </li>
      <li>
        <a href="../library/index.html">ライブラリ一覧</a>
      </li>
      <li>
        <a href="../library/_builtin.html">組み込みライブラリ</a>
      </li>
      <li>
        Exceptionクラス
      </li>
    </ol>
  </nav>

<h1>class Exception</h1>
</header>

<main>



  <nav>
    クラス・モジュールの継承リスト:
    <ol class="inline-ancestors-list">
      
        <li>
          <a href="../class/-basic-object.html">BasicObject</a>
        </li>
        
      
        <li>
          <a href="../class/-kernel.html">Kernel</a>
        </li>
        
      
        <li>
          <a href="../class/-object.html">Object</a>
        </li>
        
      
      <li>
        Exception
      </li>
    </ol>
  </nav>











<h2>要約</h2>
<p>
全ての例外の祖先のクラスです。
</p>



<h2>目次</h2>
<dl>

<dt>特異メソッド</dt>
<dd>
<ul class="class-toc">

<li><a href="#S_EXCEPTION">exception</a></li>

<li><a href="#S_EXCEPTION">new</a></li>

<li><a href="#S_TO_TTY--3F">to_tty?</a></li>

</ul>
</dd>

<dt>インスタンスメソッド</dt>
<dd>
<ul class="class-toc">

<li><a href="#I_--3D--3D">==</a></li>

<li><a href="#I_BACKTRACE">backtrace</a></li>

<li><a href="#I_BACKTRACE_LOCATIONS">backtrace_locations</a></li>

<li><a href="#I_CAUSE">cause</a></li>

<li><a href="#I_EXCEPTION">exception</a></li>

<li><a href="#I_FULL_MESSAGE">full_message</a></li>

<li><a href="#I_INSPECT">inspect</a></li>

<li><a href="#I_MESSAGE">message</a></li>

<li><a href="#I_SET_BACKTRACE">set_backtrace</a></li>

<li><a href="#I_MESSAGE">to_s</a></li>

</ul>
</dd>

</dl>




</dl>


<h2>特異メソッド</h2>
<dl>

<dt class="method-heading" id="S_EXCEPTION"><code>new(error_message = nil) -&gt; Exception</code><span class="permalink">[<a href="../method/-exception/s/exception.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-c-exception">rdoc</a>]</span></dt>
<dt class="method-heading"><code>exception(error_message = nil) -&gt; Exception</code></dt>
<dd class="method-description">
<p>
例外オブジェクトを生成して返します。
</p>
<dl>
<dt class='method-param'>[PARAM] error_message:</dt>
<dd>
エラーメッセージを表す文字列を指定します。このメッセージは属性 <a href="../method/-exception/i/message.html">Exception#message</a> の値になり、デフォルトの例外ハンドラで表示されます。
</dd>
</dl>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
e <span class="o">=</span> <span class="no">Exception</span><span class="p">.</span><span class="nf">new</span><span class="p">(</span><span class="s2">"</span><span class="s2">some message</span><span class="s2">"</span><span class="p">)</span>
<span class="nb">p</span> e         <span class="c1"># =&gt; #&lt;Exception: some message&gt;
</span><span class="nb">p</span> e<span class="p">.</span><span class="nf">message</span> <span class="c1"># =&gt; &quot;some message&quot;
</span></code></pre>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
e <span class="o">=</span> <span class="no">Exception</span><span class="p">.</span><span class="nf">exception</span><span class="p">(</span><span class="s2">"</span><span class="s2">some message</span><span class="s2">"</span><span class="p">)</span>
<span class="nb">p</span> e         <span class="c1"># =&gt; #&lt;Exception: some message&gt;
</span><span class="nb">p</span> e<span class="p">.</span><span class="nf">message</span> <span class="c1"># =&gt; &quot;some message&quot;
</span></code></pre>
</dd>


<dt class="method-heading" id="S_TO_TTY--3F"><code>to_tty? -&gt; bool</code><span class="permalink">[<a href="../method/-exception/s/to_tty=3f.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-c-to_tty-3F">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
$stderr が変更されておらず、$stderr.tty? が真の場合は true を返します。
</p>
<p>
[SEE_ALSO] <a href="../method/-exception/i/full_message.html">Exception#full_message</a>
</p>
</dd>


</dl>

<h2>インスタンスメソッド</h2>
<dl>

<dt class="method-heading" id="I_--3D--3D"><code>self == other -&gt; bool</code><span class="permalink">[<a href="../method/-exception/i/=3d=3d.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-3D-3D">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
自身と指定された other のクラスが同じであり、
message と backtrace が == メソッドで比較して等しい場合に true を返します。そうでない場合に false を返します。
</p>
<dl>
<dt class='method-param'>[PARAM] other:</dt>
<dd>
自身と比較したいオブジェクトを指定します。自身と異なるクラスのオブジェクトを指定した場合は
<a href="../method/-exception/i/exception.html">Exception#exception</a> を実行して変換を試みます。
</dd>
</dl>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="nb">require</span> <span class="s2">"</span><span class="s2">date</span><span class="s2">"</span>
<span class="k">def</span> <span class="nf">check_long_month</span><span class="p">(</span>month<span class="p">)</span>
  <span class="k">return</span> <span class="k">if</span> <span class="no">Date</span><span class="p">.</span><span class="nf">new</span><span class="p">(</span><span class="mi">2000</span>, month, <span class="o">-</span><span class="mi">1</span><span class="p">)</span><span class="p">.</span><span class="nf">day</span> <span class="o">==</span> <span class="mi">31</span>
  <span class="nb">raise</span> <span class="s2">"</span><span class="si">#{</span><span class="n">month</span><span class="si">}</span><span class="s2"> is not long month</span><span class="s2">"</span>
<span class="k">end</span>

<span class="k">def</span> <span class="nf">get_exception</span>
  <span class="k">return</span> <span class="k">begin</span>
    <span class="k">yield</span>
  <span class="k">rescue</span> <span class="o">=&gt;</span> e
    e
  <span class="k">end</span>
<span class="k">end</span>

results <span class="o">=</span> <span class="p">[</span><span class="mi">2</span>, <span class="mi">2</span>, <span class="mi">4</span><span class="p">]</span><span class="p">.</span><span class="nf">map</span> <span class="p">{</span> <span class="o">|</span>e <span class="o">|</span> get_exception <span class="p">{</span> check_long_month<span class="p">(</span>e<span class="p">)</span> <span class="p">}</span> <span class="p">}</span>
<span class="nb">p</span> results<span class="p">.</span><span class="nf">map</span> <span class="p">{</span> <span class="o">|</span>e<span class="o">|</span> e<span class="p">.</span><span class="nf">class</span> <span class="p">}</span>
<span class="c1"># =&gt; [RuntimeError, RuntimeError, RuntimeError]
</span><span class="nb">p</span> results<span class="p">.</span><span class="nf">map</span> <span class="p">{</span> <span class="o">|</span>e<span class="o">|</span> e<span class="p">.</span><span class="nf">message</span> <span class="p">}</span>
<span class="c1"># =&gt; [&quot;2 is not long month&quot;, &quot;2 is not long month&quot;, &quot;4 is not long month&quot;]
</span>
<span class="c1"># class, message, backtrace が同一のため true になる
</span><span class="nb">p</span> results<span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">==</span> results<span class="p">[</span><span class="mi">1</span><span class="p">]</span>    <span class="c1"># =&gt; true
</span>
<span class="c1"># class, backtrace が同一だが、message がことなるため false になる
</span><span class="nb">p</span> results<span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">==</span> results<span class="p">[</span><span class="mi">2</span><span class="p">]</span>    <span class="c1"># =&gt; false
</span></code></pre>
</dd>


<dt class="method-heading" id="I_BACKTRACE"><code>backtrace -&gt; [String]</code><span class="permalink">[<a href="../method/-exception/i/backtrace.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-backtrace">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
バックトレース情報を返します。
</p>
<p>
デフォルトでは
</p>
<ul>
<li>&quot;#{sourcefile}:#{sourceline}:in `#{method}'&quot;
(メソッド内の場合)</li>
<li>&quot;#{sourcefile}:#{sourceline}&quot;
(トップレベルの場合)</li>
</ul>
<p>
という形式の <a href="../class/-string.html">String</a> の配列です。
</p>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">def</span> <span class="nf">methd</span>
  <span class="nb">raise</span>
<span class="k">end</span>

<span class="k">begin</span>
  methd
<span class="k">rescue</span> <span class="o">=&gt;</span> e
  <span class="nb">p</span> e<span class="p">.</span><span class="nf">backtrace</span>
<span class="k">end</span>

<span class="c1">#=&gt; [&quot;filename.rb:2:in `methd'&quot;, &quot;filename.rb:6&quot;]
</span></code></pre>
<p>
[SEE_ALSO] <a href="../method/-exception/i/backtrace_locations.html">Exception#backtrace_locations</a>
</p>
</dd>


<dt class="method-heading" id="I_BACKTRACE_LOCATIONS"><code>backtrace_locations -&gt; [Thread::Backtrace::Location]</code><span class="permalink">[<a href="../method/-exception/i/backtrace_locations.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-backtrace_locations">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
バックトレース情報を返します。<a href="../method/-exception/i/backtrace.html">Exception#backtrace</a>に似ていますが、
<a href="../class/-thread=3a=3a-backtrace=3a=3a-location.html">Thread::Backtrace::Location</a> の配列を返す点が異なります。
</p>
<p>
現状では <a href="../method/-exception/i/set_backtrace.html">Exception#set_backtrace</a> によって戻り値が変化する事はありません。
</p>
<pre class="highlight ruby">
<span class="caption">例: test.rb</span>
<code>
<span class="nb">require</span> <span class="s2">"</span><span class="s2">date</span><span class="s2">"</span>
<span class="k">def</span> <span class="nf">check_long_month</span><span class="p">(</span>month<span class="p">)</span>
  <span class="k">return</span> <span class="k">if</span> <span class="no">Date</span><span class="p">.</span><span class="nf">new</span><span class="p">(</span><span class="mi">2000</span>, month, <span class="o">-</span><span class="mi">1</span><span class="p">)</span><span class="p">.</span><span class="nf">day</span> <span class="o">==</span> <span class="mi">31</span>
  <span class="nb">raise</span> <span class="s2">"</span><span class="si">#{</span><span class="n">month</span><span class="si">}</span><span class="s2"> is not long month</span><span class="s2">"</span>
<span class="k">end</span>

<span class="k">def</span> <span class="nf">get_exception</span>
  <span class="k">return</span> <span class="k">begin</span>
    <span class="k">yield</span>
  <span class="k">rescue</span> <span class="o">=&gt;</span> e
    e
  <span class="k">end</span>
<span class="k">end</span>

e <span class="o">=</span> get_exception <span class="p">{</span> check_long_month<span class="p">(</span><span class="mi">2</span><span class="p">)</span> <span class="p">}</span>
<span class="nb">p</span> e<span class="p">.</span><span class="nf">backtrace_locations</span>
<span class="c1"># =&gt; [&quot;test.rb:4:in `check_long_month'&quot;, &quot;test.rb:15:in `block in &lt;main&gt;'&quot;, &quot;test.rb:9:in `get_exception'&quot;, &quot;test.rb:15:in `&lt;main&gt;'&quot;]
</span></code></pre>
<p>
[SEE_ALSO] <a href="../method/-exception/i/backtrace.html">Exception#backtrace</a>
</p>
</dd>


<dt class="method-heading" id="I_CAUSE"><code>cause -&gt; Exception | nil</code><span class="permalink">[<a href="../method/-exception/i/cause.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-cause">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
self の前の例外(self が rescue 節や ensure 節の中で発生した例外の場合、その前に発生していた元々の例外)を返します。存在しない場合は nil を返します。
</p>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="k">begin</span>
    <span class="nb">raise</span> <span class="s2">"</span><span class="s2">inner</span><span class="s2">"</span>
  <span class="k">rescue</span>
    <span class="nb">raise</span> <span class="s2">"</span><span class="s2">outer</span><span class="s2">"</span>
  <span class="k">end</span>
<span class="k">rescue</span>
  <span class="nb">p</span> <span class="vg">$!</span>       <span class="c1"># =&gt; #&lt;RuntimeError: outer&gt;
</span>  <span class="nb">p</span> <span class="vg">$!</span><span class="p">.</span><span class="nf">cause</span> <span class="c1"># =&gt; #&lt;RuntimeError: inner&gt;
</span><span class="k">end</span>
</code></pre>
</dd>


<dt class="method-heading" id="I_EXCEPTION"><code>exception -&gt; self</code><span class="permalink">[<a href="../method/-exception/i/exception.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-exception">rdoc</a>]</span></dt>
<dt class="method-heading"><code>exception(error_message) -&gt; Exception</code></dt>
<dd class="method-description">
<p>
引数を指定しない場合は self を返します。引数を指定した場合 自身のコピーを生成し <a href="../method/-exception/i/message.html">Exception#message</a> 属性を error_message にして返します。
</p>
<p>
<a href="../method/-kernel/m/raise.html">Kernel.#raise</a> は、実質的に、例外オブジェクトの exception
メソッドの呼び出しです。
</p>
<dl>
<dt class='method-param'>[PARAM] error_message:</dt>
<dd>
エラーメッセージを表す文字列を指定します。
</dd>
</dl>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="c1"># ...        # 何か処理
</span><span class="k">rescue</span> <span class="o">=&gt;</span> e
  <span class="nb">raise</span> e<span class="p">.</span><span class="nf">exception</span><span class="p">(</span><span class="s2">"</span><span class="s2">an error occurs during hogehoge process</span><span class="s2">"</span><span class="p">)</span>  <span class="c1"># 詳しいエラーメッセージ
</span><span class="k">end</span>
</code></pre>
</dd>


<dt class="method-heading" id="I_FULL_MESSAGE"><code>full_message(highlight: true, order: :bottom) -&gt; String</code><span class="permalink">[<a href="../method/-exception/i/full_message.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-full_message">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
例外の整形された文字列を返します。
</p>
<p>
返される文字列は Ruby が捕捉されなかった例外を標準エラー出力に出力するときと同じ形式です。そのため、メソッド呼び出し時に $stderr が変更されておらず、$stderr.tty? が真の場合はエスケープシーケンスによる文字装飾がついています。
</p>
<dl>
<dt class='method-param'>[PARAM] highlight:</dt>
<dd>
エスケープシーケンスによる文字装飾をつけるかどうかを指定します。デフォルト値は <a href="../method/-exception/s/to_tty=3f.html">Exception.to_tty?</a> の返り値と同じです。
</dd>
<dt class='method-param'>[PARAM] order:</dt>
<dd>
:top か :bottom で指定する必要があります。バックトレースの一番奥がエラーメッセージの上(top)か下(bottom)かを指定します。デフォルト値は <a href="../method/-exception/s/to_tty=3f.html">Exception.to_tty?</a> が真なら :bottom で偽なら :top です。
</dd>
</dl>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="nb">raise</span> <span class="s2">"</span><span class="s2">test</span><span class="s2">"</span>
<span class="k">rescue</span> <span class="o">=&gt;</span> e
  <span class="nb">p</span> e<span class="p">.</span><span class="nf">full_message</span>   <span class="c1"># =&gt; &quot;\e[1mTraceback \e[m(most recent call last):\ntest.rb:2:in `&lt;main&gt;': \e[1mtest (\e[4;1mRuntimeError\e[m\e[1m)\n\e[m&quot;
</span>  <span class="vg">$stderr</span> <span class="o">=</span> <span class="vg">$stdout</span>
  <span class="nb">p</span> e<span class="p">.</span><span class="nf">full_message</span>   <span class="c1"># =&gt; &quot;test.rb:2:in `&lt;main&gt;': test (RuntimeError)\n&quot;
</span>  <span class="vg">$stderr</span> <span class="o">=</span> <span class="no">STDERR</span>
  <span class="nb">p</span> e<span class="p">.</span><span class="nf">full_message</span>   <span class="c1"># =&gt; &quot;\e[1mTraceback \e[m(most recent call last):\ntest.rb:2:in `&lt;main&gt;': \e[1mtest (\e[4;1mRuntimeError\e[m\e[1m)\n\e[m&quot;
</span><span class="k">end</span>
</code></pre>
<p>
[SEE_ALSO] <a href="../method/-exception/s/to_tty=3f.html">Exception.to_tty?</a>
</p>
</dd>


<dt class="method-heading" id="I_INSPECT"><code>inspect -&gt; String</code><span class="permalink">[<a href="../method/-exception/i/inspect.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-inspect">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
self のクラス名と message を文字列にして返します。
</p>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="nb">raise</span> <span class="s2">"</span><span class="s2">exception</span><span class="s2">"</span>
<span class="k">rescue</span>
  <span class="nb">p</span> <span class="vg">$!</span><span class="p">.</span><span class="nf">inspect</span> <span class="c1"># =&gt; &quot;#&lt;RuntimeError: exception&gt;&quot;
</span><span class="k">end</span>
</code></pre>
</dd>


<dt class="method-heading" id="I_MESSAGE"><code>message -&gt; String</code><span class="permalink">[<a href="../method/-exception/i/message.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-message">rdoc</a>]</span></dt>
<dt class="method-heading"><code>to_s -&gt; String</code></dt>
<dd class="method-description">
<p>
エラーメッセージをあらわす文字列を返します。
</p>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="mi">1</span> <span class="o">+</span> <span class="k">nil</span>
<span class="k">rescue</span> <span class="o">=&gt;</span> e
  <span class="nb">p</span> e<span class="p">.</span><span class="nf">message</span>   <span class="c1">#=&gt;  &quot;nil can't be coerced into Fixnum&quot;
</span><span class="k">end</span>
</code></pre>
</dd>


<dt class="method-heading" id="I_SET_BACKTRACE"><code>set_backtrace(errinfo) -&gt; nil | String | [String]</code><span class="permalink">[<a href="../method/-exception/i/set_backtrace.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/Exception.html#method-i-set_backtrace">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
バックトレース情報に errinfo を設定し、設定されたバックトレース情報を返します。
</p>
<dl>
<dt class='method-param'>[PARAM] errinfo:</dt>
<dd>
nil、<a href="../class/-string.html">String</a> あるいは <a href="../class/-string.html">String</a> の配列のいずれかを指定します。
</dd>
</dl>
<pre class="highlight ruby">
<span class="caption">例</span>
<code>
<span class="k">begin</span>
  <span class="k">begin</span>
    <span class="nb">raise</span> <span class="s2">"</span><span class="s2">inner</span><span class="s2">"</span>
  <span class="k">rescue</span>
    <span class="nb">raise</span> <span class="s2">"</span><span class="s2">outer</span><span class="s2">"</span>
  <span class="k">end</span>
<span class="k">rescue</span>
  <span class="vg">$!</span><span class="p">.</span><span class="nf">backtrace</span> <span class="c1"># =&gt; [&quot;/path/to/test.rb:5:in `rescue in &lt;main&gt;'&quot;, &quot;/path/to/test.rb:2:in `&lt;main&gt;'&quot;]
</span>  <span class="vg">$!</span><span class="p">.</span><span class="nf">set_backtrace</span><span class="p">(</span><span class="p">[</span><span class="s2">"</span><span class="s2">dummy1</span><span class="s2">"</span>, <span class="s2">"</span><span class="s2">dummy2</span><span class="s2">"</span><span class="p">]</span><span class="p">)</span>
  <span class="vg">$!</span><span class="p">.</span><span class="nf">backtrace</span> <span class="c1"># =&gt; [&quot;dummy1&quot;, &quot;dummy2&quot;]
</span><span class="k">end</span>
</code></pre>
</dd>


</dl>

</main>

<footer id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>

  <a href="https://github.com/rurema/doctree/issues/new" id="feedback-link">フィードバックを送る</a>
  
  <script>if (window.URLSearchParams) { document.getElementById("feedback-link").search = new URLSearchParams({'body': document.location}); }</script>
</footer>
</body>
</html>
