<!DOCTYPE html>
<html lang="ja-JP">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Language" content="ja-JP">
  <link rel="stylesheet" type="text/css" href="../../../style.css">
  <link rel="icon" type="image/png" href="../../../rurema.png">
  
  <title>instance method Exception#cause (Ruby 2.4.0)</title>
</head>
<body>

<p>
<a href="../../../doc/index.html">Ruby 2.4.0 リファレンスマニュアル</a>
&gt; <a href="../../../library/index.html">ライブラリ一覧</a>
&gt; <a href="../../../library/_builtin.html">組み込みライブラリ</a>
&gt; <a href="../../../class/-exception.html">Exceptionクラス</a>
&gt; cause

</p>


<h1>instance method Exception#cause</h1>
<dl class="methodlist">

<dt class="method-heading" id="I_CAUSE"><code>cause -&gt; Exception | nil</code><span class="permalink">[<a href="../../../method/-exception/i/cause.html">permalink</a>][<a href="http://docs.ruby-lang.org/en/2.4.0/Exception.html#method-i-cause">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
self の前の例外(self が rescue 節や ensure 節の中で発生した例外の場合、
その前に発生していた元々の例外)を返します。存在しない場合は nil を返し
ます。
</p>
</dd>


</dl>


<div id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>
</div>
</body>
</html>
